### ISSUE TITLE
Move footer to the bottom of the page (where it belongs)

### ISSUE THREAD

**Issue by maraf** [maraf/Money#244]
- https://www.freecodecamp.org/news/how-to-keep-your-footer-where-it-belongs-59c6aa05c59c/

```css
body {
  margin: 0 auto;
  max-width: 900px;
  position: relative;
  min-height: 100vh;
  background: yellow;
}

#content-wrap {
  padding-bottom: 2.5rem;    /* Footer height */
}

#footer {
  position: absolute;
  bottom: 0;
  width: 100%;
  height: 2.5rem;            /* Footer height */
  background: blue;
}
```
